# Generated by Django 3.2.3 on 2021-08-18 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(default='achievement.png', upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language_logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.png', upload_to='logos/')),
                ('birth', models.DateField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('agend', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('goal', models.CharField(blank=True, max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, default='www.example.com')),
                ('description', models.TextField()),
                ('languages', models.ManyToManyField(related_name='portfolio', to='resume.Language')),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.person')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('company_logo', models.ImageField(default='default.png', upload_to='logos/')),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
                ('date_end', models.DateField(default=django.utils.timezone.now)),
                ('position', models.CharField(max_length=30)),
                ('duty', models.CharField(max_length=50)),
                ('company_site', models.URLField(default='www.company.info', max_length=100)),
                ('languages', models.ManyToManyField(related_name='experience', to='resume.Language')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.person')),
                ('portfolio', models.ManyToManyField(blank=True, default='www.portfolio.com', to='resume.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('school_logo', models.ImageField(default='default.png', upload_to='logos/')),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, default='Bechelor Degree', max_length=30)),
                ('gpa', models.FloatField(blank=True)),
                ('major', models.CharField(blank=True, max_length=20)),
                ('minor', models.CharField(blank=True, max_length=20)),
                ('is_graduated', models.BooleanField(default=False)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.person')),
            ],
        ),
    ]
