# Generated by Django 3.2.3 on 2021-08-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_web',
            field=models.URLField(default='www.college.edu', max_length=100),
        ),
    ]
